NUM_CLASS = 7 #class 数量
BATCH_SIZE = 2
PROPOSAL_NUM = 5 # M
CAT_NUM = 3 # K
INPUT_SIZE = (448, 448)  # (w, h)
LR = 0.001
WD = 1e-4
SAVE_FREQ = 1
resume = ''
test_model = 'model.ckpt'
save_dir = './models/'
